# Generated by Django 4.0.6 on 2022-07-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_project_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tag',
            new_name='tags',
        ),
    ]
