# Generated by Django 4.0.6 on 2022-07-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_tag_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_app',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.URLField(blank=True),
        ),
    ]
